# Generated by Django 3.2.5 on 2021-07-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pokemons',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
